POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFyc2thIiwiaWQiOiI2MGQxZGIyYzNmNzBhNDMwMzRiODgyODgiLCJpYXQiOjE2MjQzODQxMTZ9.zYDdKRbhUdu8oXi6k2XfvkElRfCfC-6SOlJAQ2oLcNo

{
  "title": "Authorized book 2",
  "author": "Arska edelleen",
  "url": "www.arskansivu.com",
  "likes": 100
}